### PR TITLE
Initial Support for 8.1

### PR DESCRIPTION
**Pull request by gsteel**
|    Q          |   A
|-------------- | ------
| New Feature   | yes
| QA            | yes

- Removes the ZF Bridge and marks as conflict with zend equivalent
- Add 8.1 to composer
- Add return type will change where required
- bumps stdlib to minimum version with 8.1 support
- bumps dev deps

### CODE REVIEW

**Comment by gsteel** [comment]
The psalm upgrade is unavoidable, regardless of 8.1 support because ^4.6 will update to ^4.10 anyway - It causes a bunch of new errors which I've fixed the majority. Can the remaining be added to the baseline?

**Comment by Ocramius** [comment]
I think these could be put in baseline, yes:

```
Error: The declared return type 'iterable<array-key, mixed>' for Laminas\Paginator\Adapter\Iterator::getItems is more specific than the inferred return type 'Laminas\Paginator\SerializableLimitIterator|array<empty, empty>' (see https://psalm.dev/197)
Error: The type 'Laminas\Paginator\SerializableLimitIterator' is more general than the declared return type 'iterable<array-key, mixed>' for Laminas\Paginator\Adapter\Iterator::getItems (see https://psalm.dev/197)
Error: Laminas\Cache\StorageFactory is marked deprecated (see https://psalm.dev/098)

```

On the various `PluginManager` implementations, we should probably fix the name of arguments.

**Review by Ocramius — APPROVED** [review]
LGTM :ship: 

Thanks @gsteel!

**Comment by Slamdunk** [comment]
Completion proposed in https://github.com/laminas/laminas-paginator/pull/33

**Pull request merged**
