### PR TITLE
PHP 8.3 support added

### PR DESCRIPTION
**Pull request by glo71317**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Comment by froschdesign** [comment]
@glo71317 
The validation of the PHPUnit configuration (`phpunit.xml.dist`) fails: https://github.com/laminas/laminas-paginator/actions/runs/6493438436/job/17634391697?pr=57#step:3:311

**Comment by glo05363** [comment]
@gsteel would you please check here https://github.com/laminas/laminas-paginator/blob/4b2f26bd748bc9d212f323de9caee03144804400/psalm-baseline.xml#L222 I have baselined the particular failing check https://github.com/laminas/laminas-paginator/actions/runs/6742756417/job/18329425939?pr=57 , somehow it is not passing, please give me a suggestion here.

**Comment by glo71317** [comment]
@gsteel PR is green now Can you please review the PR and merge?

**Review by Ocramius — APPROVED** [review]
Thanks @glo71317!

**Pull request merged**
