### PR TITLE
Complete PHP 8.1 support, drop PHP 7.3

### PR DESCRIPTION
**Pull request by Slamdunk**
This should complete https://github.com/laminas/laminas-paginator/pull/32

The mandatory update of `laminas/laminas-coding-standard` adds ` declare(strict_types=1);` everywhere, don't know if this has to be considered a BC break or not

### CODE REVIEW

**Comment by Ocramius** [comment]
@Slamdunk a `composer update` when setting `config.platform.php: 7.3.99` should help here

**Comment by Slamdunk** [comment]
Opened the PR just before lunch: fixed now, thanks :+1:

**Review by Ocramius — APPROVED** [review]
🚢

**Comment by Ocramius** [comment]
Thanks @Slamdunk!

**Comment by samsonasik** [comment]
@Ocramius DbSelect seems missing `[\ReturnTypeWillChange]`, I created PR https://github.com/laminas/laminas-paginator/pull/34 for it.

**Pull request merged**
